global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['host.docker.internal:5010']
  - job_name: 'worker'
    static_configs:
      - targets: ['host.docker.internal:5030']
  - job_name: 'identityservice'
    static_configs:
      - targets: ['host.docker.internal:8000']