global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['web:80']
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:80']
  - job_name: 'identityservice'
    static_configs:
      - targets: ['identityservice:80']