apiVersion: v1
kind: Service
metadata:
  name: mssql-svc
spec:
  type: NodePort
  selector:
    app: mssql # label of the pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30036
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql
    spec:
      hostname: mssql
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 1433
        env:
          - name: MSSQL_SA_PASSWORD
            value: P@ssw0rd
          - name: MSSQL_PID
            value: Developer
          - name: ACCEPT_EULA
            value: "1"
        volumeMounts:
          # - name: sqldata2
          #   mountPath: /var/opt/mssql
          - name: mssqldb
            mountPath: /var/opt/mssql
      # initContainers:
      # - name: mssql-change-owner
      #   image: busybox:latest
      #   command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
      #   volumeMounts:
      #   - name: sqldata2
      #     mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-data
        # - name: sqldata2
        #   hostPath:
        #     path: "/Users/marina/Projects/BlazorApp1/.data/sql-edge"      
        #     type: DirectoryOrCreate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-data-pv
spec:
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/Users/marina/Projects/BlazorApp1/.data/sql-edge"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - my-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi